# This is a basic workflow to help you get started with Actions

name: Build tool binary

# Controls when the workflow will run
on:
  workflow_dispatch:
  
  push:
    tags: '*'

defaults:
  run:
    shell: bash

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout sources
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # To fetch all tags and branches

      - name: setup golang
        uses: actions/setup-go@v2
        id: go
        with:
          go-version: 1.17
  build:
    needs: [setup]
    runs-on: ubuntu-latest
    steps:
      - name: checkout sources
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # To fetch all tags and branches

      - name: build machineconfig generator tool for hugepages
        run: make dist-hugepages-mc-genarator
        
      - name: upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: build/_output/bin/hugepages-machineconfig-generator
  
  # release:
  #   needs: [build]
  #   runs-on: ubuntu-latest
  #   steps:
      - name: checkout sources
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # To fetch all tags and branches

      - name: download again the build artifacts
        uses: actions/download-artifact@v2
        with:
          name: build-artifacts

      - name: release the tool binary 
        uses: ncipollo/release-action@v1
        with:
          name: hugepagesmcgenartor
          artifacts: build/_output/bin/hugepages-machineconfig-generator
