
name: Build hugepages-machineconfig-generator tool binary

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: checkout sources
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 

      - name: setup golang
        uses: actions/setup-go@v2
        id: go
        with:
          go-version: 1.17
  build:
    needs: [setup]
    runs-on: ubuntu-latest
    steps:
      - name: checkout sources
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 

      - name: build machineconfig generator tool for hugepages
        run: make dist-hugepages-mc-genarator

      - name: release the tool binary 
        uses: ncipollo/release-action@v1
        with:
          name: hugepagesmcgenartor
          artifacts: build/_output/bin/hugepages-machineconfig-generator
